# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `path_expander` gem.
# Please instead update this file by running `bin/tapioca gem path_expander`.

# source://path_expander//lib/path_expander.rb#15
class PathExpander
  # source://path_expander//lib/path_expander.rb#38
  def initialize(args, glob, path = T.unsafe(nil)); end

  # source://path_expander//lib/path_expander.rb#21
  def args; end

  # source://path_expander//lib/path_expander.rb#21
  def args=(_arg0); end

  # source://path_expander//lib/path_expander.rb#49
  def expand_dirs_to_files(*dirs); end

  # source://path_expander//lib/path_expander.rb#165
  def filter_files(files, ignore); end

  # source://path_expander//lib/path_expander.rb#26
  def glob; end

  # source://path_expander//lib/path_expander.rb#26
  def glob=(_arg0); end

  # source://path_expander//lib/path_expander.rb#31
  def path; end

  # source://path_expander//lib/path_expander.rb#31
  def path=(_arg0); end

  # source://path_expander//lib/path_expander.rb#144
  def process; end

  # source://path_expander//lib/path_expander.rb#87
  def process_args; end

  # source://path_expander//lib/path_expander.rb#63
  def process_file(path); end

  # source://path_expander//lib/path_expander.rb#131
  def process_flags(flags); end
end

# source://path_expander//lib/path_expander.rb#16
PathExpander::VERSION = T.let(T.unsafe(nil), String)
