# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `timeout` gem.
# Please instead update this file by running `bin/tapioca gem timeout`.

# source://timeout//lib/timeout.rb#25
module Timeout
  private

  # source://timeout//lib/timeout.rb#169
  def timeout(sec, klass = T.unsafe(nil), message = T.unsafe(nil), &block); end

  class << self
    # source://timeout//lib/timeout.rb#127
    def ensure_timeout_thread_created; end

    # source://timeout//lib/timeout.rb#169
    def timeout(sec, klass = T.unsafe(nil), message = T.unsafe(nil), &block); end

    private

    # source://timeout//lib/timeout.rb#97
    def create_timeout_thread; end
  end
end

# source://timeout//lib/timeout.rb#50
Timeout::CONDVAR = T.let(T.unsafe(nil), Thread::ConditionVariable)

# source://timeout//lib/timeout.rb#36
class Timeout::Error < ::RuntimeError
  class << self
    # source://timeout//lib/timeout.rb#37
    def handle_timeout(message); end
  end
end

# source://timeout//lib/timeout.rb#29
class Timeout::ExitException < ::Exception
  # source://timeout//lib/timeout.rb#30
  def exception(*_arg0); end
end

# source://timeout//lib/timeout.rb#139
Timeout::GET_TIME = T.let(T.unsafe(nil), Method)

# source://timeout//lib/timeout.rb#51
Timeout::QUEUE = T.let(T.unsafe(nil), Thread::Queue)

# source://timeout//lib/timeout.rb#52
Timeout::QUEUE_MUTEX = T.let(T.unsafe(nil), Thread::Mutex)

# source://timeout//lib/timeout.rb#57
class Timeout::Request
  # source://timeout//lib/timeout.rb#60
  def initialize(thread, timeout, exception_class, message); end

  # source://timeout//lib/timeout.rb#58
  def deadline; end

  # source://timeout//lib/timeout.rb#70
  def done?; end

  # source://timeout//lib/timeout.rb#76
  def expired?(now); end

  # source://timeout//lib/timeout.rb#89
  def finished; end

  # source://timeout//lib/timeout.rb#80
  def interrupt; end
end

# source://timeout//lib/timeout.rb#53
Timeout::TIMEOUT_THREAD_MUTEX = T.let(T.unsafe(nil), Thread::Mutex)

# source://timeout//lib/timeout.rb#26
Timeout::VERSION = T.let(T.unsafe(nil), String)
